// The claim keypair lives in two places on purpose, and the whole security
// property is that they never swap.
//
// The PUBLIC half is committed to acceptance/claim-keys.json, because the
// student's browser needs it to seal an address and holding it lets anyone
// encrypt and nobody decrypt. The PRIVATE half is a hub ENVIRONMENT secret on
// `provisioning` - main branch only, no repository-level copy - because it
// decrypts every student's institutional email address out of the public event
// archive.
//
// Both keys are P-256 and both are base64url, which is exactly what makes the
// mistake easy to make and invisible once made: a private key pasted into the
// keys file looks like the thing that belongs there. It is 184 characters where
// a public key is 122, and that is what this checks.
import { test } from "node:test";
import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import { join, dirname } from "node:path";
import { fileURLToPath } from "node:url";

import {
  CLAIM_PRIVATE_KEY_LENGTH,
  CLAIM_PUBLIC_KEY_LENGTH,
  generateClaimKeypair,
  encryptClaim,
  decryptClaim,
} from "../lib/claim.mjs";

const here = dirname(fileURLToPath(import.meta.url));
const root = join(here, "..");
const KEYS_FILE = join(root, "acceptance", "claim-keys.json");

const file = JSON.parse(readFileSync(KEYS_FILE, "utf8"));

test("the keys file has the shape both readers expect", () => {
  assert.equal(typeof file.keys, "object");
  assert.ok(file.keys !== null);
  // `current` names which key new claims are sealed to. Null is legitimate:
  // it means no keypair has been minted yet, which is the state this file
  // ships in - and it must be an explicit null rather than a missing key, so
  // "not configured" and "field absent" cannot be confused.
  assert.ok("current" in file, "current must be present even when null");
  assert.ok(file.current === null || typeof file.current === "string");
});

test("nothing private-key-shaped is ever in the public keys file", () => {
  // The mistake this exists to catch. A P-256 PKCS8 private key is 184
  // base64url characters; an SPKI public key is 122. Both look like the same
  // kind of blob.
  const offenders = [];
  for (const [kid, value] of Object.entries(file.keys)) {
    if (typeof value !== "string") {
      offenders.push(`${kid}: not a string`);
      continue;
    }
    if (value.length === CLAIM_PRIVATE_KEY_LENGTH) {
      offenders.push(`${kid}: ${value.length} chars - THIS IS A PRIVATE KEY`);
    } else if (value.length !== CLAIM_PUBLIC_KEY_LENGTH) {
      offenders.push(`${kid}: ${value.length} chars, expected ${CLAIM_PUBLIC_KEY_LENGTH}`);
    }
    if (!/^[A-Za-z0-9_-]+$/.test(value)) offenders.push(`${kid}: not base64url`);
  }
  assert.deepEqual(offenders, [], `acceptance/claim-keys.json:\n${offenders.join("\n")}`);
});

test("the raw file text carries no PKCS8 header", () => {
  // Belt and braces on the length check, and it catches a partial paste too.
  // Every P-256 PKCS8 key generated by WebCrypto starts with the same 36
  // characters, which is the same anchor PUBLIC_TEXT_RULES uses for the
  // invitation key.
  const raw = readFileSync(KEYS_FILE, "utf8");
  const pkcs8Prefix = "MIGHAgEAMBMGByqGSM49AgEGCCqGSM49";
  assert.ok(
    !raw.includes(pkcs8Prefix),
    "a PKCS8 private key header appears in the PUBLIC claim keys file",
  );
});

test("current, when set, names a key that is actually present", () => {
  // A `current` pointing at a missing kid seals claims to nothing and fails at
  // the accept button rather than at deploy time.
  if (file.current === null) {
    assert.deepEqual(file.keys, {}, "no current key means no keys yet");
    return;
  }
  assert.ok(file.keys[file.current], `current is "${file.current}" but that kid is not in keys`);
});

test("a key of the published length really does seal a claim the hub can open", async () => {
  // Proves the length this file enforces is the length the crypto wants -
  // otherwise the guard could be pinning a number nothing verifies.
  const { publicKey, privateKey } = await generateClaimKeypair();
  assert.equal(publicKey.length, CLAIM_PUBLIC_KEY_LENGTH);
  assert.equal(privateKey.length, CLAIM_PRIVATE_KEY_LENGTH);

  const payload = await encryptClaim({
    publicKey, email: "a@student.pxl.be", githubId: 1, assignmentId: "x",
  });
  assert.equal((await decryptClaim({ privateKey, payload })).email, "a@student.pxl.be");

  // And the halves are not interchangeable: sealing to the private key fails.
  await assert.rejects(() =>
    encryptClaim({ publicKey: privateKey, email: "a@student.pxl.be", githubId: 1, assignmentId: "x" }),
  );
});
