// lib/types.d.mts is generated from schemas/, and this is what keeps it true.
//
// TWO CHECKS, AND THE SECOND ONE IS THE POINT. Regenerating and comparing
// catches a stale file, but it is built from the same function as the
// generator, so it validates its own bugs (CLAUDE.md: "a scripted transform
// must be verified by something that does not share its logic"). The property
// sweep below reads the schema JSON itself and asks the emitted TEXT whether
// each name is there, which is a path the generator has no part in.
//
// Why this matters more than it looks: the whole reason `npm run typecheck`
// exists is to catch a schema field spelled wrong - `s.status` where the field
// is `submission_status` is `undefined` on every row, and `!== 'x'` is then
// always true. A types file that has drifted from the schemas says the wrong
// names confidently, which is worse than saying nothing.

import { test } from "node:test";
import assert from "node:assert/strict";
import { readFileSync, readdirSync } from "node:fs";
import { join, dirname } from "node:path";
import { fileURLToPath } from "node:url";

import { renderTypes, typeNameFor, TYPES_PATH, SCHEMA_DIR } from "../scripts/generate-types.mjs";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const emitted = readFileSync(TYPES_PATH, "utf8");

test("the committed file is what the schemas produce", () => {
  assert.equal(
    emitted,
    renderTypes(),
    "lib/types.d.mts is stale. Run: npm run types",
  );
});

test("it says it is generated, so nobody edits it by hand", () => {
  assert.match(emitted.split("\n")[0], /GENERATED BY scripts\/generate-types\.mjs/);
  assert.match(emitted, /npm run types/);
});

test("every schema has a type, named the same way every time", () => {
  const files = readdirSync(SCHEMA_DIR).filter((f) => f.endsWith(".schema.json"));
  assert.ok(files.length >= 15, `expected the schema directory, found ${files.length} files`);
  for (const file of files) {
    const name = typeNameFor(file);
    assert.match(
      emitted,
      new RegExp(`^export type ${name} = `, "m"),
      `${file} has no type in lib/types.d.mts`,
    );
  }
});

test("EVERY property a schema declares is in the emitted text", () => {
  // Read from the schema JSON, never through the generator: this is the half
  // that can disagree with it. Names only - what the types are is the
  // generator's business, and a wrong type is a readable mistake where a
  // missing name is an invisible one.
  const missing = [];
  for (const file of readdirSync(SCHEMA_DIR).filter((f) => f.endsWith(".schema.json"))) {
    const schema = JSON.parse(readFileSync(join(SCHEMA_DIR, file), "utf8"));
    for (const name of propertyNames(schema)) {
      const key = /^[A-Za-z_$][A-Za-z0-9_$]*$/.test(name) ? name : JSON.stringify(name);
      if (!emitted.includes(`${key}?:`)) missing.push(`${file}: ${name}`);
    }
  }
  assert.deepEqual(missing, [], "these schema properties are in no emitted type");
});

test("and every property in the emitted text is one a schema declares", () => {
  // The other direction, which is what stops the file inventing a field. A name
  // invented here is a name somebody will read off a type and then never find
  // in a document.
  const declared = new Set();
  for (const file of readdirSync(SCHEMA_DIR).filter((f) => f.endsWith(".schema.json"))) {
    for (const name of propertyNames(JSON.parse(readFileSync(join(SCHEMA_DIR, file), "utf8")))) {
      declared.add(name);
    }
  }
  const invented = [...emitted.matchAll(/^\s+"?([A-Za-z_$][A-Za-z0-9_$]*)"?\?:/gm)]
    .map((m) => m[1])
    .filter((name) => !declared.has(name));
  assert.deepEqual([...new Set(invented)], [], "these properties are in no schema");
});

test("the generated file is not imported at runtime by anything", () => {
  // It is types only - there is no `lib/types.mjs` to import. A real import of
  // `./types.mjs` would resolve to nothing and take the SPA's page down with
  // it, so the only legal mention is inside a JSDoc comment.
  const offenders = [];
  for (const file of readdirSync(join(root, "lib")).filter((f) => f.endsWith(".mjs"))) {
    const src = readFileSync(join(root, "lib", file), "utf8");
    // A real import statement, as opposed to the `import("./types.mjs")` form
    // that only ever appears inside a JSDoc type.
    if (/^\s*import\s[^\n]*from\s+["']\.\/types\.mjs["']/m.test(src)) offenders.push(file);
  }
  assert.deepEqual(offenders, [], "lib/types.mjs does not exist at runtime - these would fail at load");
});

/** Every property name a schema declares, at any depth. */
function propertyNames(node, out = new Set()) {
  if (!node || typeof node !== "object") return out;
  if (Array.isArray(node)) {
    for (const item of node) propertyNames(item, out);
    return out;
  }
  for (const [key, value] of Object.entries(node)) {
    if (key === "properties" && value && typeof value === "object" && !Array.isArray(value)) {
      for (const name of Object.keys(value)) out.add(name);
    }
    propertyNames(value, out);
  }
  return out;
}
