// GENERATED BY scripts/generate-types.mjs - DO NOT EDIT.
//
// The documents in schemas/, as TypeScript, so `npm run typecheck` knows the
// field names. Every property is optional: this types a document that has been
// READ, where any field may be absent, and `required` is Ajv's job at the
// moment one is written. Regenerate with `npm run types`.

/** An acceptance record stored in acceptances/<assignment-id>/<login>.json within a PXL Classroom control repository. (schemas/acceptance.schema.json) */
export type Acceptance = {
  schema_version?: 1;
  assignment_id?: string;
  github_login?: string;
  github_id?: number;
  accepted_at?: string;
  star_event_ref?: string;
  team_slug?: string;
  team_name?: string;
  status?: "accepted" | "provisioning" | "provisioned" | "failed";
  claimed_email?: string;
  claim_verified?: boolean;
  claim_domain_allowed?: boolean;
  reused_existing_repo?: boolean;
};

/** An assignment definition stored in assignments/<id>.yml within a PXL Classroom control repository. (schemas/assignment.schema.json) */
export type Assignment = {
  schema_version?: 1;
  id?: string;
  title?: string;
  description?: string;
  organization?: string;
  template?: {
    owner?: string;
    repository?: string;
    repository_id?: number;
  };
  assignment_type?: "individual" | "group";
  group_config?: {
    max_team_size?: number;
    min_team_size?: number;
    formation_mode?: "self-service" | "pre-assigned";
    allow_team_creation?: boolean;
    team_name_prefix?: string;
    unassigned_fallback?: "block" | "self-service";
  };
  repository_name_pattern?: string;
  opens_at?: string;
  deadline_at?: string;
  timezone?: string;
  submission_ref?: string;
  submission_marker?: {
    type?: "commit_message";
    value?: string;
    multiple?: boolean;
    max_hand_ins?: number;
  };
  student_permission?: "pull" | "triage" | "push" | "maintain" | "admin";
  acceptance_mode?: "self-service";
  require_claim?: boolean;
  cohort?: string[];
  roster_mode?: "enforced" | "claim" | "open";
  claim_domains?: string[];
  claim_address_format?: boolean;
  late_policy?: "report" | "block";
  existing_repo_policy?: "reuse" | "refuse";
  state?: "draft" | "published" | "closed" | "archived";
  max_acceptances?: number;
  lock_down_enabled?: boolean;
  org_scoped_lock?: boolean;
  feedback_pr?: boolean;
  feedback_pr_baseline_branch?: string;
  template_grades?: boolean;
  autograde?: {
    enabled?: boolean;
    execution_environment?: "lecturer_local" | "github_actions";
    visibility?: "public" | "private";
    tests?: Array<{
      id?: string;
      type?: "run" | "io" | "python";
      command?: string;
      script?: string;
      stdin?: string;
      expected_stdout?: string;
      image?: string;
      timeout_s?: number;
      points?: number;
    }>;
  };
  invite_token?: string;
  invite_nonce?: string;
  invite_expires_at?: string;
  invite_key?: string;
  invite_pubkey?: string;
};

/** One student's binding of a GitHub account to an institutional email address, at students/claims/<github_id>.json in the private control repository (schemas/claim.schema.json) */
export type Claim = {
  schema_version?: 1;
  github_login?: string;
  github_id?: number;
  email?: string;
  domain_allowed?: boolean;
  claim_verified?: boolean;
  student_number?: string;
  claimed_at?: string;
  claimed_via?: string;
  replaces?: {
    email?: string;
    claimed_at?: string;
  };
  history?: Array<{
    email?: string;
    claimed_at?: string;
  }>;
};

/** One element of `Claim.history`. */
export type ClaimHistory = NonNullable<Claim["history"]>[number];

/** The cross-assignment roll-up at reports/dashboard.json, and the only file the org overview reads (schemas/dashboard.schema.json) */
export type Dashboard = {
  schema_version?: 1;
  assignments?: Record<string, {
    title?: string;
    state?: "draft" | "published" | "closed" | "archived";
    opens_at?: string;
    deadline_at?: string;
    timezone?: string;
    max_acceptances?: number;
    total_students?: number;
    accepted?: number;
    provisioned?: number;
    on_time?: number;
    late?: number;
    no_submission?: number;
    with_repo_faults?: number;
    generated_at?: string;
  }>;
  generated_at?: string;
};

/** Download manifest file written to the submissions directory by PXL Classroom CLI or SPA. (schemas/download-manifest.schema.json) */
export type DownloadManifest = {
  schema_version?: 1;
  org?: string;
  assignment_id?: string;
  generated_at?: string;
  students?: Array<{
    login?: string;
    archive_sha?: string;
    archive_branch?: string;
    archive_branch_url?: string;
    downloaded_at?: string;
  }>;
};

/** One element of `DownloadManifest.students`. */
export type DownloadManifestStudent = NonNullable<DownloadManifest["students"]>[number];

/** Per-student autograder result, written to grading/<assignment-id>/<login>.json in the control repo by `pxl-classroom grade`. (schemas/grading-result.schema.json) */
export type GradingResult = {
  schema_version?: 1;
  assignment_id?: string;
  github_login?: string;
  archive_sha?: string;
  archive_branch?: string;
  graded_at?: string;
  graded_by?: string;
  runner?: "docker" | "host" | "github_actions";
  total_points?: number;
  earned_points?: number;
  tests?: Array<{
    id?: string;
    passed?: boolean;
    points?: number;
    earned?: number;
    duration_ms?: number;
    exit_code?: number;
    timed_out?: boolean;
    stdout?: string;
    stderr?: string;
  }>;
};

/** One element of `GradingResult.tests`. */
export type GradingResultTest = NonNullable<GradingResult["tests"]>[number];

/** Cohort grading roll-up, written to grading/<assignment-id>/summary.json in the control repo (schemas/grading-summary.schema.json) */
export type GradingSummary = {
  schema_version?: 1;
  assignment_id?: string;
  generated_at?: string;
  graded_by?: string;
  runner?: "docker" | "host" | "github_actions";
  students?: Array<{
    login?: string;
    earned_points?: number;
    total_points?: number;
    graded_at?: string;
    ci_status?: string;
    ci_run_url?: string;
    score_source?: "annotation-json" | "points" | "conclusion" | "manual";
    graded_sha?: string;
    decided_by?: {
      kind?: "commit" | "score";
      by?: string;
      at?: string;
      reason?: string;
    };
    hand_ins?: {
      used?: number;
      allowed?: number;
      extra?: number;
      graded_sha?: string;
      graded_number?: number;
      ignored?: Array<{
        sha?: string;
        date?: string;
        pushed_at?: string;
        on_branch?: boolean;
        number?: number;
        reason?: "over-limit" | "late";
      }>;
    };
  }>;
  failed?: Array<{
    login?: string;
    reason?: string;
    hand_ins?: {
      used?: number;
      allowed?: number;
      extra?: number;
      graded_sha?: string;
      graded_number?: number;
      ignored?: Array<{
        sha?: string;
        date?: string;
        pushed_at?: string;
        on_branch?: boolean;
        number?: number;
        reason?: "over-limit" | "late";
      }>;
    };
  }>;
};

/** One element of `GradingSummary.students`. */
export type GradingSummaryStudent = NonNullable<GradingSummary["students"]>[number];

/** One element of `GradingSummary.failed`. */
export type GradingSummaryFailed = NonNullable<GradingSummary["failed"]>[number];

/** Per-repo limit overrides stored at <org>/pxl-classroom-control/limits-overrides.json (schemas/limits-overrides.schema.json) */
export type LimitsOverrides = {
  schema_version?: 1;
  repos?: Record<string, Record<string, number>>;
};

/** Global per-SKU weekly usage limits (schemas/limits.schema.json) */
export type Limits = {
  schema_version?: 1;
  weekly_limits?: Array<{
    sku?: string;
    unit?: string;
    limit?: number;
  }>;
};

/** One element of `Limits.weekly_limits`. */
export type LimitsWeeklyLimit = NonNullable<Limits["weekly_limits"]>[number];

/** What a deadline finalize did to one assignment's cohort, at lockdowns/<assignment-id>/lockdown-record.json (schemas/lockdown-record.schema.json) */
export type LockdownRecord = {
  schema_version?: 1;
  assignment_id?: string;
  deadline_at?: string;
  executed_at?: string;
  finalize_attempts?: number;
  first_finalized_at?: string;
  observer_run?: string;
  locked_at?: string;
  lock_method?: "org-ruleset" | "ruleset" | "demotion" | "none";
  org_ruleset_id?: number;
  late_policy?: "report" | "block";
  locked_count?: number;
  error_count?: number;
  no_submission_count?: number;
  deferred_count?: number;
  reopened_count?: number;
  unfreezable_count?: number;
  max_uncertainty_seconds?: number;
  results?: Array<{
    github_login?: string;
    team_slug?: string;
    repo_name?: string;
    repo_id?: number;
    snapshot_sha?: string;
    snapshot_ref?: string;
    pushed_at?: string;
    lockdown_at?: string;
    lock_method?: "org-ruleset" | "ruleset" | "demotion" | "none" | null;
    reconstructed?: boolean;
    no_submission?: boolean;
    demoted?: boolean;
    permission_after?: string;
    verified?: boolean;
    unfreezable_reason?: "org-owner" | null;
    deferred_until?: string;
    deferred_reason?: string;
    uncertainty_seconds?: number;
    reopened_at?: string;
  }>;
};

/** One element of `LockdownRecord.results`. */
export type LockdownRecordResult = NonNullable<LockdownRecord["results"]>[number];

/** A point-in-time observation of a student repository's state, stored in observations/<assignment-id>/<login>/<timestamp>.json (schemas/observation.schema.json) */
export type Observation = {
  schema_version?: 1;
  type?: "snapshot";
  assignment_id?: string;
  github_login?: string;
  repo_id?: number;
  observed_at?: string;
  ref?: string;
  sha?: string;
  commit_count?: number;
  commit_date?: string;
  late_commit_count?: number;
  commit_message?: string;
  author_name?: string;
  author_email?: string;
  observer_run?: string;
  collection_type?: "scheduled" | "manual" | "deadline" | "lockdown" | "preservation";
} | {
  schema_version?: 1;
  type?: "tagged-submission";
  assignment_id?: string;
  github_login?: string;
  repo_id?: number;
  observed_at?: string;
  tag?: string;
  declared_at?: string;
  tagged_sha?: string;
  observer_run?: string;
};

/** Lecturer overrides for a student on an assignment, stored in overrides/<assignment-id>/<login>.json. (schemas/override.schema.json) */
export type Override = {
  schema_version?: 1;
  assignment_id?: string;
  github_login?: string;
  overrides?: Array<{
    type?: "github_login" | "acceptance_state" | "repository" | "deadline_extension" | "hand_in_allowance" | "submission_sha" | "manual_score" | "late_status" | "exemption" | "annotation";
    value?: unknown;
    reason?: string;
    overridden_by?: string;
    overridden_at?: string;
    run_id?: number;
  }>;
};

/** One element of `Override.overrides`. */
export type OverrideOverride = NonNullable<Override["overrides"]>[number];

/** Registry of organizations participating in PXL Classroom (schemas/participating-orgs.schema.json) */
export type ParticipatingOrgs = {
  schema_version?: 1;
  orgs?: Array<{
    login?: string;
    budget_owner_login?: string;
    budget_owner_email?: string;
    overrides?: Record<string, number>;
  }>;
};

/** One element of `ParticipatingOrgs.orgs`. */
export type ParticipatingOrgsOrg = NonNullable<ParticipatingOrgs["orgs"]>[number];

/** A deadline report for an assignment, stored in reports/<assignment-id>.json. (schemas/report.schema.json) */
export type Report = {
  schema_version?: 1;
  assignment_id?: string;
  generated_at?: string;
  generator_version?: string;
  source_revision?: string;
  live_refreshed_at?: string;
  live_refreshed_by?: string;
  teams?: Array<{
    team_slug?: string;
    team_name?: string;
    members?: string[];
    repo_name?: string;
    repo_url?: string;
    repo_id?: number;
    submission_status?: "on-time" | "late" | "no-submission" | "unknown";
    latest_observed_sha?: string;
    commit_count?: number;
    lock_down_at?: string;
    preservation_status?: string;
    preserved_sha?: string;
    archive_repo?: string;
    archive_ref?: string;
    under_capacity?: boolean;
    warnings?: string[];
    seeded_from?: Record<string, unknown>;
  }>;
  students?: Array<{
    github_login?: string;
    team_slug?: string;
    team_name?: string;
    student_number?: string;
    full_name?: string;
    email?: string;
    class_group?: string;
    author_name?: string;
    author_email?: string;
    acceptance_state?: string;
    reused_existing_repo?: boolean;
    claimed_email?: string;
    claim_verified?: boolean;
    claim_domain_allowed?: boolean;
    claim_format_allowed?: boolean;
    repo_id?: number;
    repo_name?: string;
    repo_url?: string;
    submission_status?: "on-time" | "late" | "no-submission" | "unknown";
    last_on_time_sha?: string;
    last_on_time_observed_at?: string;
    first_late_sha?: string;
    first_late_observed_at?: string;
    latest_observed_sha?: string;
    latest_observed_at?: string;
    commit_date?: string;
    latest_commit_date?: string;
    commit_message?: string;
    latest_commit_message?: string;
    commit_count?: number;
    late_commit_count?: number;
    uncertainty_interval_seconds?: number;
    effective_deadline_at?: string;
    override_applied?: boolean;
    override_reason?: string;
    lockdown_delay_seconds?: number;
    tagged_submission_tag?: string;
    tagged_submission_sha?: string;
    tagged_submission_observed_at?: string;
    tagged_submission_declared_at?: string;
    lock_down_at?: string;
    lock_down_outcome?: string;
    preservation_status?: "preserved" | "pending" | "failed" | "not-required" | null;
    preserved_sha?: string;
    archive_repo?: string;
    archive_ref?: string;
    warnings?: string[];
    reopened_at?: string;
  }>;
};

/** One element of `Report.teams`. */
export type ReportTeam = NonNullable<Report["teams"]>[number];

/** One element of `Report.students`. */
export type ReportStudent = NonNullable<Report["students"]>[number];

/** A repository record stored in repositories/<assignment-id>/<login>.json within a PXL Classroom control repository. (schemas/repository-record.schema.json) */
export type RepositoryRecord = {
  schema_version?: 1;
  assignment_id?: string;
  github_login?: string;
  team_slug?: string;
  members?: string[];
  repo_id?: number;
  repo_name?: string;
  repo_url?: string;
  created_at?: string;
  provisioned_by_run?: string;
  student_permission?: string;
  access_state?: "invited" | "active" | "removed" | "unknown";
  last_checked_at?: string;
  feedback_pr_number?: number;
  feedback_pr_url?: string;
  feedback_pr_baseline_sha?: string;
};

/** What was deleted, when, by whom, and where the code still is (schemas/retired-manifest.schema.json) */
export type RetiredManifest = {
  schema_version?: 1;
  assignment_id?: string;
  title?: string;
  deleted_at?: string;
  deleted_by?: string;
  broker_repo_deleted?: string;
  archive_repo?: string;
  preserved_submissions?: number;
  org_ruleset_removed?: boolean;
  removed_paths?: string[];
};

/** Student roster stored in students/roster.yml within a PXL Classroom control repository. (schemas/roster.schema.json) */
export type Roster = {
  schema_version?: 2;
  students?: Array<{
    student_number?: string;
    full_name?: string;
    email?: string;
    email_source?: "commit" | "claim";
    class_group?: string;
    github_login?: string;
    github_id?: number;
    active?: boolean;
    team_slug?: string;
    team_name?: string;
    source?: "import" | "accepted";
    promoted_from?: {
      assignment_id?: string;
      accepted_at?: string;
      promoted_at?: string;
      promoted_by?: string;
    };
  }>;
};

/** One element of `Roster.students`. */
export type RosterStudent = NonNullable<Roster["students"]>[number];

/** A record of a starter code synchronization run, stored in syncs/<assignment-id>/<sync-id>.json in the control repository. (schemas/sync-record.schema.json) */
export type SyncRecord = {
  schema_version?: 1;
  sync_id?: string;
  assignment_id?: string;
  synced_at?: string;
  synced_by?: string;
  template_repo?: string;
  template_sha?: string;
  template_base_sha?: string;
  selected_files?: string[];
  status?: "running" | "completed" | "stopped";
  run_id?: number;
  run_url?: string;
  started_at?: string;
  finished_at?: string;
  total_students?: number;
  remaining?: number;
  per_student_range?: boolean;
  all_files?: boolean;
  pr_title?: string;
  pr_body?: string;
  created_issues?: boolean;
  summary?: {
    total?: number;
    auto_merged?: number;
    pr_opened?: number;
    skipped?: number;
    failed?: number;
  };
  results?: Array<{
    github_login?: string;
    team_slug?: string;
    repo_name?: string;
    outcome?: "auto-merged" | "pr-opened" | "merged-and-pr" | "skipped-up-to-date" | "skipped-no-repo" | "failed";
    files_merged?: number;
    files_conflicted?: number;
    from_sha?: string;
    from_source?: "synced" | "generated" | "first-commit" | "other-template" | "unknown";
    files_kept?: number;
    commit_sha?: string;
    pr_number?: number;
    pr_url?: string;
    issue_number?: number;
    issue_url?: string;
    error?: string;
    issue_assignees?: string[];
    issue_error?: string;
  }>;
};

/** One element of `SyncRecord.results`. */
export type SyncRecordResult = NonNullable<SyncRecord["results"]>[number];

/** A team definition stored in teams/<assignment-id>/<team-slug>.json within a PXL Classroom control repository. (schemas/team.schema.json) */
export type Team = {
  schema_version?: 1;
  assignment_id?: string;
  team_slug?: string;
  team_name?: string;
  members?: string[];
  max_members?: number;
  created_at?: string;
  created_by?: string;
  repo_name?: string;
  repo_id?: number;
  repo_url?: string;
  vacant?: boolean;
  seeded_from?: {
    source?: "assignment" | "roster";
    assignment_id?: string;
    assignment_title?: string;
    seeded_at?: string;
    seeded_by?: string;
  };
};

/** lockdowns/<assignment-id>/unlocked/<github-login>.json - one student repository reopened after the deadline (schemas/unlock-record.schema.json) */
export type UnlockRecord = {
  schema_version?: 1;
  assignment_id?: string;
  github_login?: string;
  team_slug?: string;
  repo_name?: string;
  unlocked_at?: string;
  unlocked_by?: string;
  reason?: string;
  lock_method?: "org-ruleset" | "ruleset" | "demotion";
  permission_restored?: "pull" | "triage" | "push" | "maintain" | "admin";
  snapshot_sha?: string;
};
