// PXL Classroom - student repositories that exist with no record of them.
//
// An acceptance creates the repository first and records it last, in a push to
// the org's control repo. When that push fails the student has a repository
// and an invitation, and the control repo has neither an acceptance nor a
// repository record - so the student is on no list, and the collector, the
// deadline lock, the archive and the report, which all work from the records,
// never touch them. The student cannot tell: their side worked.
//
// Measured 2026-09-28 on PXL-SNB-Security-Expert2627: thirteen students
// accepted in one minute, one run lost the push five times, and that student
// was outside the list for two days until somebody read the hub's runs. The
// acceptance now notifies when its own push fails; this is the same question
// asked from the other side, nightly, for whatever else can lose a record.
//
// REPORT ONLY. Writing the missing record here would have the nightly create
// acceptances nobody made - for a repository somebody generated by hand from
// the template, too. The lecturer presses Retry, which runs every gate.
//
// Pure: the caller lists the org and asks GitHub about each candidate.

import { collidingRepoNames } from "./assignment-collision.mjs";

/** The states in which students can hold a repository of the assignment. */
const LIVE_STATES = ["published", "closed"];

const bare = (name) => String(name ?? "").split("/").pop().toLowerCase();

/**
 * Repositories an assignment's name pattern produces that no record names.
 *
 * CANDIDATES, not findings: a name can match a pattern by coincidence, so the
 * caller confirms each one was generated from the assignment's template
 * (`generatedFrom`) before saying anything.
 *
 * @param {object} args
 * @param {Array<{id: string, state?: string, repository_name_pattern?: string}>} args.assignments every assignment document in the org
 * @param {Map<string, Iterable<string>>} args.recorded assignment id -> repository names its records and team manifests name (`owner/name` or bare)
 * @param {string[]} args.repoNames every repository name in the organization
 * @returns {Array<{assignment_id: string, repo: string}>}
 */
export function unrecordedCandidates({ assignments, recorded, repoNames }) {
  const live = (assignments || []).filter((a) => a?.id && LIVE_STATES.includes(a.state) && a.repository_name_pattern);
  const out = [];
  for (const a of live) {
    const known = new Set([...(recorded?.get(a.id) ?? [])].map(bare));
    const others = live.filter((o) => o.id !== a.id);
    for (const repo of collidingRepoNames(a.repository_name_pattern, repoNames, others)) {
      if (!known.has(bare(repo))) out.push({ assignment_id: a.id, repo });
    }
  }
  return out;
}

/**
 * Was this repository generated from this template? From `GET /repos/{o}/{r}`.
 *
 * `true` only on GitHub's own `template_repository`. A repository that merely
 * has a matching name - made by hand, left by another tool - is not ours to
 * report. `null` when the read failed: not evidence either way, and a
 * repository that could not be read is not reported.
 *
 * @param {{ok?: boolean, status?: number, data?: any}|null|undefined} res
 * @param {{owner?: string, repository?: string}|null|undefined} template
 * @returns {boolean|null}
 */
export function generatedFrom(res, template) {
  if (!res?.ok || !res.data) return null;
  const from = String(res.data.template_repository?.full_name ?? "").toLowerCase();
  const want = `${template?.owner ?? ""}/${template?.repository ?? ""}`.toLowerCase();
  return Boolean(from) && want !== "/" && from === want;
}

/**
 * The student login a repository name carries, when the pattern is the
 * ordinary `prefix{github_login}suffix`; null for any other shape.
 *
 * @param {string} pattern
 * @param {string} repo
 * @returns {string|null}
 */
export function loginFromRepoName(pattern, repo) {
  const parts = String(pattern ?? "").split("{github_login}");
  if (parts.length !== 2 || /[{}]/.test(parts[0] + parts[1])) return null;
  const name = String(repo ?? "");
  const [prefix, suffix] = parts;
  if (name.length <= prefix.length + suffix.length) return null;
  if (!name.toLowerCase().startsWith(prefix.toLowerCase()) || !name.toLowerCase().endsWith(suffix.toLowerCase())) return null;
  return name.slice(prefix.length, name.length - suffix.length);
}

// ONE LINE PER REPOSITORY, written by the nightly into the notice and read back
// by the Organization page, which puts a Retry, links and the advice that fits
// beside each (2026-10-08: the notice said "press Retry on the assignment page",
// where such a student has no row to press it on). The writer and the reader
// are this pair, round-tripped by tests/unrecorded-repos.test.mjs.

/** The notice line for one finding: `- \`repo\` - student \`login\` (assignment \`id\`)`. */
export function unrecordedNoticeLine({ repo, login = null, assignment_id }) {
  return `- \`${repo}\`${login ? ` - student \`${login}\`` : ""} (assignment \`${assignment_id}\`)`;
}

const LINE = /^- `([^`]+)`(?: - student `([^`]+)`)? \(assignment `([^`]+)`\)\s*$/gm;

/**
 * The findings a notice's details name, as `unrecordedNoticeLine` wrote them.
 * @returns {Array<{repo: string, login: string|null, assignmentId: string}>}
 */
export function parseUnrecordedLines(details) {
  return [...String(details || "").matchAll(LINE)].map(([, repo, login, assignmentId]) => ({ repo, login: login || null, assignmentId }));
}
