#!/usr/bin/env node
// PXL Classroom - turn MANUAL.md into data the SPA can render.
//
// The SPA has no markdown dependency and does not get one for this. The whole
// file is parsed here, at build time, into a small JSON tree that Vue renders
// with real components - so nothing goes through `v-html` and the manual picks
// up the app's own tokens for free.
//
// The cost of that choice is that only the subset below exists. It is the
// subset MANUAL.md is written in, and widening it means editing this file:
//
//   # Title                     the document title, once
//   ## Heading {#id}            a topic; the id is what the UI asks for
//   ### Heading                 a section inside a topic
//   - item                      a bullet (one level, no nesting)
//   paragraph text              anything else
//   **bold**  *em*  `code`      inline, non-nesting
//   [text](#id) [text](https://…)   internal and external links
//
// Anything it does not recognise stays literal rather than vanishing: a silently
// dropped sentence in a help topic is worse than an ugly one.
//
// Output is gitignored and regenerated by `predev`/`prebuild`, so it can never
// be stale relative to MANUAL.md. The guard on the topic ids is
// tests/manual-topics.test.mjs, which deliberately does NOT import this file.

import { readFileSync, writeFileSync, mkdirSync } from "node:fs";
import { join, dirname } from "node:path";
import { fileURLToPath, pathToFileURL } from "node:url";

const ROOT = join(dirname(fileURLToPath(import.meta.url)), "..");
const SOURCE = join(ROOT, "MANUAL.md");
const OUT_DIR = join(ROOT, "frontend", "src", "generated");
const OUT = join(OUT_DIR, "manual.json");

/**
 * `## Heading` - a topic. Its id is GitHub's own slug of the heading text.
 *
 * An explicit `{#id}` was the first design and it was wrong in a way only
 * visible outside the app: GitHub does not support that syntax, so every
 * heading rendered with the braces showing and every cross-topic link was dead
 * for anyone reading MANUAL.md on github.com. Deriving the id means one anchor
 * that works in both places.
 *
 * The usual objection to derived ids - rename the heading and every link to it
 * breaks silently - does not apply here, because lib/manual-topics.mjs pins the
 * ids and tests/manual-topics.test.mjs fails loudly on exactly that.
 */
const TOPIC = /^##\s+(.+?)\s*$/;

/** GitHub's heading slug, and deliberately the same rule tests/doc-refs.test.mjs uses. */
export function slug(heading) {
  return heading
    .replace(/`/g, "")
    .replace(/\[([^\]]*)\]\([^)]*\)/g, "$1")
    .replace(/[*_]/g, "")
    .toLowerCase()
    .replace(/[^\p{L}\p{N} _-]/gu, "")
    .trim()
    .replace(/ /g, "-");
}
const SUBHEAD = /^###\s+(.+?)\s*$/;
const BULLET = /^[-*]\s+(.+?)\s*$/;
const TITLE = /^#\s+(.+?)\s*$/;

// Inline runs, longest-first so `**bold**` is not eaten by `*em*`.
const INLINE = /(\*\*[^*]+\*\*|\*[^*]+\*|`[^`]+`|\[[^\]]+\]\([^)]+\))/g;

/**
 * Split one line of prose into inline nodes.
 *
 * Returns plain strings for ordinary text so the common case stays cheap, and
 * objects for the four things that need markup.
 *
 * @param {string} text
 * @returns {Array<string|{t: string, v: string, href?: string}>}
 */
export function parseInline(text) {
  const out = [];
  let last = 0;
  for (const m of text.matchAll(INLINE)) {
    if (m.index > last) out.push(text.slice(last, m.index));
    const tok = m[0];
    if (tok.startsWith("**")) out.push({ t: "strong", v: tok.slice(2, -2) });
    else if (tok.startsWith("`")) out.push({ t: "code", v: tok.slice(1, -1) });
    else if (tok.startsWith("[")) {
      const cut = tok.indexOf("](");
      out.push({ t: "link", v: tok.slice(1, cut), href: tok.slice(cut + 2, -1) });
    } else out.push({ t: "em", v: tok.slice(1, -1) });
    last = m.index + tok.length;
  }
  if (last < text.length) out.push(text.slice(last));
  return out;
}

/**
 * Parse the whole document.
 *
 * @param {string} src
 * @returns {{title: string, intro: Array<object>, topics: Array<object>}}
 */
export function parseManual(src) {
  const lines = src.split(/\r?\n/);
  const doc = { title: "", intro: [], topics: [] };

  /** Blocks currently being appended to: the intro, or the newest topic. */
  let sink = doc.intro;
  let para = [];
  let bullets = [];

  const flush = () => {
    if (para.length) {
      sink.push({ type: "p", spans: parseInline(para.join(" ")) });
      para = [];
    }
    if (bullets.length) {
      sink.push({ type: "ul", items: bullets.map(parseInline) });
      bullets = [];
    }
  };

  for (const raw of lines) {
    const line = raw.trim();

    if (!line) { flush(); continue; }

    const topic = TOPIC.exec(line);
    if (topic) {
      flush();
      doc.topics.push({ id: slug(topic[1]), title: topic[1], blocks: [] });
      sink = doc.topics[doc.topics.length - 1].blocks;
      continue;
    }

    const sub = SUBHEAD.exec(line);
    if (sub) { flush(); sink.push({ type: "h3", text: sub[1] }); continue; }

    const title = TITLE.exec(line);
    if (title && !doc.title) { flush(); doc.title = title[1]; continue; }

    const bullet = BULLET.exec(line);
    if (bullet) { if (para.length) flush(); bullets.push(bullet[1]); continue; }

    if (bullets.length) flush();
    para.push(line);
  }
  flush();
  return doc;
}

function main() {
  const src = readFileSync(SOURCE, "utf8");
  const doc = parseManual(src);

  if (doc.topics.length === 0) {
    // An empty manual would build cleanly and render a help drawer with nothing
    // in it. Fail here instead.
    console.error("build-manual: MANUAL.md declared no `## Heading` topics");
    process.exit(1);
  }

  const seen = new Set();
  for (const t of doc.topics) {
    if (seen.has(t.id)) {
      console.error(`build-manual: duplicate topic id {#${t.id}} - the UI could not say which it meant`);
      process.exit(1);
    }
    seen.add(t.id);
  }

  mkdirSync(OUT_DIR, { recursive: true });
  writeFileSync(OUT, JSON.stringify(doc, null, 2) + "\n", "utf8");
  console.log(`build-manual: ${doc.topics.length} topics -> ${OUT.replace(ROOT, ".")}`);
}

// pathToFileURL, not a hand-built `file://` string: on Windows the hand-built
// one is short a slash and the guard is false forever, so the script exits 0
// having written nothing.
if (process.argv[1] && import.meta.url === pathToFileURL(process.argv[1]).href) main();
